version: '3.8'

services:
  # keycloak
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: playaru/keycloak-russian:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_URL: http://localhost:8080
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
      - ldap



  # app
  app_db:
    image: postgres:14
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - ./postgres-app-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_REPORTS_URL: http://localhost:8001

  auth:
    build:
      context: ./backend/bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      REACT_APP_FRONTEND_URL: http://localhost:3000
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_DOCKER_URL: http://host.docker.internal:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend
      DATABASE_HOST: app_db
      DATABASE_PORT: 5432
      DATABASE_USER: app_user
      DATABASE_PASSWORD: app_password
      DATABASE_NAME: app_db
    extra_hosts:
      - "keycloack.local:host-gateway"
    depends_on:
      - app_db

  reports:
    build:
      context: ./backend/bionicpro-reports
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      CLICKHOUSE_HOST: http://clickhouse:8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    depends_on:
      - clickhouse



  # ldap
  ldap:
    image: osixia/openldap:1.5.0
    command: --copy-service
    volumes:
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      - LDAP_ORGANISATION=example-com
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"



  # airflow
  airflow-postgres:
    image: postgres:16.0
    volumes:
      - ./airflow/postgres-airflow-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - airflow
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-webserver:
    image: apache/airflow:2.10.5-python3.11
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/dags/sql:/opt/airflow/dags/sql
      - ./airflow/data:/opt/airflow/data
    ports:
      - "8081:8080"
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: clickhouse-connect pandas apache-airflow-providers-postgres
    command: bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow webserver"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-scheduler:
    image: apache/airflow:2.10.5-python3.11
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/dags/sql:/opt/airflow/dags/sql
      - ./airflow/data:/opt/airflow/data
    command: scheduler
    depends_on:
      airflow-postgres:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: clickhouse-connect pandas apache-airflow-providers-postgres

  airflow-init:
    image: apache/airflow:2.10.5-python3.11
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/dags/sql:/opt/airflow/dags/sql
      - ./airflow/data:/opt/airflow/data
    depends_on:
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow

    command: >
      bash -c " airflow db init && airflow users create \ --username admin \ --firstname admin \ --lastname admin \ --role Admin \ --email admin@sample.ru \ --password admin 
      
      "

  clickhouse:
    image: clickhouse/clickhouse-server:24.8-alpine
    platform: linux/amd64
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init-clickhouse.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default

volumes:
  clickhouse_data: